require('plugin.autobrackets')
require('plugin.cmp')
require('plugin.comment')
require('plugin.lsp')
require('plugin.lualine')
require('plugin.nvimtree')
require('plugin.telescope')
require('plugin.toggleterm')
